### ISSUE TITLE
List of things different in production and dev environment

### ISSUE THREAD

**Issue by rndexe** [an-online-reading-room/reading-room-backend#1]
1. Node version is 14.7.3 in prod, while 16.14.2 in dev
2. config/database.js files are very different, not sure how things are working still

**Comment by opheliagame** [comment]
@rndexe we should definitely resolve the node version issue, what do you suggest we should make it to?
about the database.js file i have tried so much to figure out but cannot understand why in production strapi doesnt seem to use the file inside `config/env/production`. it continues to use the file outside so essentially dev and production are using the same file but the env variables are changing

**Comment by rndexe** [comment]
Probably need to add these in package.json

NODE_ENV=production yarn build

And 

NODE_ENV=production yarn start

Node version imo we should be on 16.x.x, sveltekit also needs the same and 14's support would end next year

**Comment by opheliagame** [comment]
i have set the node version to 16, which is the same we are using for sveltekit and added NODE_ENV to commands in package.json
