### ISSUE TITLE
cascade on delete

### ISSUE THREAD

**Issue by opheliagame** [an-online-reading-room/reading-room-backend#3]
@rndexe on deleting an item, it's relations become orphans, is there a way to cascade on delete? I haven't been able to find anything in v4 about this

**Comment by rndexe** [comment]
research suggested using a lifecycle hook life beforeDelete

Using strapi entityService to get all the related relations

beforeDelete {

const entries = await strapi.entityService.findOne('api::article.article', id, {
  populate: '*',
});

Then loop over the entries to delete them one by one

forEach relation
await strapi.entityService.delete('api::realtion.realation', realtion.id);

}

**Comment by opheliagame** [comment]
@rndexe we can try this then, will have to be a bit careful tho, so i will prepare a chart linking the diff entities and when what should be deleted
